language: cpp
sudo: false

addons:
  apt:
    packages:
      - g++-5
      - clang-3.6
      - cmake
      - cmake-data
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
install:

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6

before_script:
  - cd ${TRAVIS_BUILD_DIR}/test/
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./szlib

